### ISSUE TITLE
Import failed line 397 and line 162

### ISSUE THREAD

**Issue by Stephan-4711** [patrick0525/Python-Opn-isc-kea#1]
The sample files provided are working. My config.xml does not work, I don't understand the output error. the descr it self look good.

Traceback (most recent call last):
  File "/root/kea/opnsense_isc_to_kea_reservations.py", line 397, in <module>
    json_to_opnsense_xml(entry_path, kea_input_file, kea_output_file)
  File "/root/kea/opnsense_isc_to_kea_reservations.py", line 162, in json_to_opnsense_xml
    ET.SubElement(reservation,"description").text = str(item["descr"])

**Comment by patrick0525** [comment]
When u do: 
python3 opnsense_isc_to_kea_reservations.py [your_config-OPNsense*.xml]

It produces a new  opnsense_isc_static_lease.json
It should be an json array.

Compare ur opnsense_isc_static_lease.json to the GitHub’s opnsense_isc_static_lease.json

Any differences? Diff or use beyond-compare. Use notepad++ to see if there any hidden characters.


It is stopping because the json obj's 'descr' key/value pair has something incorrect.

I wrote the Python script using an older opnsense config file.

**Comment by Stephan-4711** [comment]
I now solved it, by marking all reservations inside of the webinterface, copy them to an excel file, exported the reserverations as csv and reimported it to KEA Server with the opnsense csv import option inside of KEA menue. Was way easier. Case can be closed

**Comment by patrick0525** [comment]
I can look at ur config.xml and investigate but I need to 1st create a branch so u push it in. Do want to push in ur config.xml? I understand ur concern regarding router data sensitivity.
